"""Long-form prose for the rk-overview pages. Kept separate from the chart machinery.

This is the owner's explainer repo: unlike rk-findings (auto-generated, numbers only),
these pages carry interpretation and architecture narrative, drafted with Claude and
maintained by the owner. rk-findings stays the machine-truth; anything here that
disagrees with it is wrong here.
"""

ABOUT_NOTE = (
    "rk-overview is the human-maintained explainer for the rk project. The companion site "
    "rk-findings is generated by the harness every cycle and carries the authoritative numbers; "
    "a frozen copy from 2026-08-30 is snapshotted under this site. Drafted with Claude, edited "
    "and owned by the author.")

INTRO = """
<p>The <strong>rk project</strong> is an unattended, months-long search for explicit
Runge&ndash;Kutta tableaus that minimise <em>end-to-end error in Q15 fixed-point arithmetic at a
fixed cycle budget on Cortex-M0+</em> &mdash; instead of the textbook criterion, truncation error
in exact real arithmetic.</p>

<p>The falsifiable claim: classical tableaus were derived assuming exact arithmetic. On an
FPU-less microcontroller in Q15, at step sizes a real controller would use, roundoff dominates
truncation &mdash; so the classically optimal coefficients are not the practically optimal ones,
and nobody has searched the gap between. Prior work (RKTK and its line) searches tableaus
numerically for order and error constants; it does not price coefficients against a hardware
cost model, and it does not evaluate in fixed point. That narrow gap is the project.</p>

<p>Three repositories with three trust levels do the work: <code>rk-harness</code> holds the
verifier, evaluator and cost models and is mounted <em>read-only</em> into the run container;
<code>rk-work</code> accumulates the append-only archive of every verified tableau;
<code>rk-findings</code> receives an auto-generated site of numbers each cycle. This site,
<code>rk-overview</code>, is the human layer on top.</p>
"""

HEADLINES = """
<p>Everything below was measured by the harness; the findings snapshot carries the full tables.</p>
<ul>
<li><strong>The anchor result.</strong> rk4 and rk38 are both 4-stage order-4 methods with the
same stability polynomial. Under a 1-cycle multiplier rk4 is cheaper (33 vs 36 cycles/step);
under a 32-cycle multiplier rk38 is cheaper (64 vs 85). Which method to ship depends on which
multiplier the chip shipped with &mdash; the thesis demonstrated in two textbook methods.</li>
<li><strong>A proof, not a search, at order 2.</strong> The 2-stage order-2 family admits exactly
16 exactly-representable points (a21 = m/2^s, s &le; 6). Exhaustive enumeration shows
<code>midpoint</code> is the cheapest at 11 slow cycles &mdash; optimal within that space, with
<code>heun2</code> two cycles behind. A neighbouring point, a21 = -1/4 with b = (3, -2), has the
better held-out error at 16 cycles.</li>
<li><strong>Roundoff dominates where it matters.</strong> The day-one falsification experiment:
rk4 spends 56% of its cycles on coefficient arithmetic under the fast multiplier (36% under the
slow one), and its Q15 error stops improving below h &asymp; 0.16 on the damped oscillator while
float64 keeps falling &mdash; the roundoff/truncation crossover sits squarely in the practical
range, so the project proceeds.</li>
<li><strong>Floor rounding is a first-class actor.</strong> Q15 multiplies floor toward negative
infinity (that is what ARM's <code>ASRS</code> does), and the resulting -&frac12;-LSB bias per
term is the same order as the per-step dynamics at these budgets: at equal cycle budget Euler's
<em>search-set</em> error undercuts rk4's, and the stiff <code>rc_thermal</code> problem
collapses toward zero for every method. Swap floor for round-to-nearest and the ordering flips
&mdash; see the rounding chart on the results page.</li>
</ul>
"""

ARCH_SECTIONS = """
<h2>Trust boundaries</h2>
<p>The design assumes the searching agent will, if permitted, optimise the scorer instead of the
score. Four boundaries make that unprofitable:</p>
<ul>
<li><strong>The scorer cannot be edited.</strong> <code>rk-harness</code> is mounted read-only
into the container, and the container refuses to start unless the sha256 over the ten verifier
files (coeffrep, orderconditions, verifier, costmodel, evaluator, problems, and the four fixture
files) matches a pinned value. Every archive record carries the verifier hash that scored it.</li>
<li><strong>No credential reaches the agent.</strong> The GitHub token stays on the host: the
container receives a filtered environment, only ever <em>commits</em> into the mounted
checkouts, and the host watchdog pushes with the owner's own credentials.</li>
<li><strong>The model never grades itself.</strong> Confidence tiers
(heldout_verified / search_only / unreplicated) and hypothesis verdicts
(supported / refuted / inconclusive) are computed by code from the archive. The tier strings do
not appear in any LLM prompt template; a directive carrying an unknown key &mdash; including a
tier &mdash; is rejected, not ignored.</li>
<li><strong>Model-written code is quarantined.</strong> A model-authored problem executes only
after an AST-checked import allowlist (math only, no dunders, no I/O), determinism and time
bounds, a range check, a reference solution, and a promotion gate; it can then join only the
held-out set, so the optimiser can never be steered toward a problem the model invented.</li>
</ul>

<h2>The cycle loop</h2>
<p>The runner executes one idempotent cycle at a time; a crash at any point costs at most one
cycle because the archive is append-only with fsync, state is written atomically, and replay
discards a torn trailing line. Each cycle: replay the archive &rarr; ask the encourager for an
action &rarr; produce candidates &rarr; verify each &rarr; evaluate in Q15 under three cost
models at equal cycle budget &rarr; assign a tier against the cell's incumbent &rarr; append
&rarr; resolve open hypotheses &rarr; regenerate the findings site &rarr; commit &rarr; save
state.</p>

<h2>Verification, in order</h2>
<p>Nine checks, cheap before expensive, all pure code: NOT_EXPLICIT, ROW_SUM_INCONSISTENT,
DYADIC_IMPOSSIBLE (order &ge; 3 with all-dyadic coefficients is provably empty &mdash; the
order-3 condition sums to 1/3, which no dyadic rational equals), ORDER_NOT_MET (exact rational
residuals over rooted trees, never floats), COEFF_UNREPRESENTABLE (a range check &mdash;
inexactness like 1/3 is <em>recorded</em>, never rejected), Q15_OVERFLOW (2&times; amplitude
margin), UNSTABLE, NO_ASYMPTOTIC_WINDOW (the measured-order fit found no consistent slope run),
NAN_OR_INF. Only the primary cost model's columns gate verification; the slow and AVR columns
are archive breadth.</p>

<h2>Arithmetic, exactly</h2>
<p>States are Q15 (int16, scale 2<sup>-15</sup>). A multiply is <code>(a*b) &gt;&gt; 15</code>
with an arithmetic shift &mdash; flooring toward negative infinity, matching ASRS and
deliberately not matching C's truncation. Addition overflow raises rather than wraps, so
overflow becomes a verifier rejection instead of a silent wrong answer. Coefficients are not Q15:
each is an integer-and-shift pair m/2<sup>s</sup> (rk4's 1 and kutta3's 2 do not fit [-1, 1)),
and inexact representations contribute a recorded quantisation error. Cost is driven by CSD
(non-adjacent-form) weight &mdash; 3/8 is dyadic yet costs two shifts and an add &mdash; with
every coefficient priced at min(shift-add expansion, multiply).</p>

<h2>Where candidates come from</h2>
<p>Phase 0 and 1 are exhaustive enumerations (16 points at order 2; 5,094 exact 3-stage order-3
points), so their results are proofs of optimality within the enumerated space, and the site
labels them that way. Phases 2 and 3 run CMA-ES islands over the strictly-lower triangle of A
snapped to dyadics, with b then solved <em>exactly</em> over the rationals from the b-linear
order conditions &mdash; snapping b would make order &ge; 3 impossible by the dyadic theorem.
When the requested order is not exactly solvable for a snapped A (order 4 rarely is), the
projection falls back to the highest solvable order &ge; 2 and the candidate is verified at the
order it actually achieves.</p>

<h2>The outer loop: a research partner, not a sampler</h2>
<p>The LLM (Codex, plan-billed, authenticated on the host and mounted read-only) never touches
the inner loop. It emits JSON directives that can only narrow the search &mdash; target order,
stage counts, structural constraints &mdash; validated against a schema where unknown keys are
rejections. Directives are requested every few cycles (and on every escalation) and reused in
between; calls stop at a plan-usage cap. On HYPOTHESIZE escalations it proposes falsifiable
hypotheses whose ids and verdicts are assigned by code and whose predicates must parse under a
closed grammar (a hand-written parser; no eval anywhere near model output). A literature loop
web-searches a rotating topic every ~50 cycles and feeds the digest into every prompt, so the
directives and hypotheses are grounded in existing research. The digests and the model's prose
interpretation are published on the findings site, clearly labelled and softened so the site's
banned-words guard holds.</p>

<h2>The host layer</h2>
<p>A PowerShell watchdog polls every 10 s: stale heartbeat &rarr; kill; spend over cap or disk
under 5 GB &rarr; stop; laptop on battery or foreground CPU load &rarr; pause (and resume);
plus the host-side pushes. Operational knobs &mdash; container resources, auto-stop after N
minutes/cycles, LLM throttles, watchdog thresholds &mdash; live in a workspace
<code>config.json</code> edited by <code>configure.py</code>; scientific thresholds are
deliberately not configurable because changing them invalidates the archive. A read-only watcher
window renders the whole state live; Ctrl+C in it cannot touch the run.</p>

<h2>What the pre-flight actually caught</h2>
<p>The checklist was executed as a program, not a document, and it earned its keep: the crash
-recovery drill exposed that a runner killed mid-seeding never finished writing the classical
baselines (fixed: seeding is idempotent per hash, every cycle); the trust-boundary probe showed
the original PAT could push the verifier repo despite the handoff's 403 test passing (fixed by
moving the credential out of the container entirely); the first live archive build tripped the
banned-words guard on a hypothesis containing &ldquo;beats&rdquo; &mdash; the guard doing
exactly its job against text nobody reviewed.</p>
"""

# (title, original_summary, as_built) — original_summary condensed from DESIGN.md; as_built
# annotates what the code actually does today.
DECISIONS = [
    ("The problem is quantization, not coefficient prettiness",
     "In floating point, h·b constant-folds and 1/3 costs the same as 0.25; the premise only "
     "survives in fixed point on an FPU-less MCU, where a power-of-two coefficient becomes a "
     "shift. Scope narrowed accordingly.",
     "Kept, and measured: the falsification run puts coefficient arithmetic at 56% of rk4's "
     "cycles under the fast multiplier (36% slow) with a roundoff/truncation crossover at "
     "h ≈ 0.16 on the damped oscillator — comfortably above the 15% kill line."),
    ("Order ≥ 3 admits no all-dyadic tableau",
     "Dyadic rationals are closed under + and ×; Σ b·c² = 1/3 is not dyadic. The objective is "
     "minimising non-dyadic multiplies subject to order, encoded as reject code "
     "DYADIC_IMPOSSIBLE so the search never wastes a cycle on an empty region.",
     "Kept — and it shaped the search space itself: A is snapped to dyadics but b is solved "
     "exactly over the rationals from the b-linear order conditions, because snapping b would "
     "run into this very theorem. The verifier rejects all-dyadic order-3 claims without "
     "evaluating them (tests V5–V7)."),
    ("Static cycle counting, not simulation, not hardware",
     "The inner loop is branchless straight-line code, so summing ISA cycle costs gives an "
     "exact count and a genuine WCET figure; host contention cannot corrupt the metric.",
     "Kept, sharpened: the count is fully analytic from the tableau (no compiler or "
     "disassembly in the loop). The model is anchored to hardware by one hand-counted ARMv6-M "
     "sequence (13 cycles fast / 75 slow) that a test reproduces exactly, and emit_c exists "
     "for a one-time human cross-check."),
    ("Cortex-M0+ primary; AVR advisory; two M0+ multiplier variants",
     "M0+ has no FPU/divide/long-multiply, so fixed point is forced; running a 1-cycle and a "
     "32-cycle multiplier model costs nothing and turns hardware-aware into a demonstrated "
     "effect if the ranking changes.",
     "Kept — the ranking does change (rk4 33 vs rk38 36 fast; rk38 64 vs rk4 85 slow). AVR "
     "stays advisory in a stronger sense than planned: after a live candidate was rejected on "
     "an AVR-column infinity, verification was restricted to primary-model columns only; the "
     "slow/AVR numbers are archive breadth."),
    ("Q15, wrapping semantics, overflow as a rejection",
     "Q31 must be synthesized on M0+; saturation costs a compare-and-branch and destroys exact "
     "counting. Overflow at 2× amplitude is a verifier rejection — a property of the method, "
     "not a runtime cost.",
     "Kept, with one addition the spec missed: rc_thermal's derivative (−11 at t=0) times its "
     "state scale exceeds Q15, so derivatives carry a per-problem power-of-two scale "
     "(DERIV_SCALE, 1/8 there) undone in the step via h. Floor rounding turned out to be a "
     "first-class experimental variable — see the rounding chart."),
    ("Classical optimizer in the inner loop, LLM in the outer loop",
     "A 6-parameter space has gradients; CMA-ES beats an LLM mutation operator for free. The "
     "LLM decides what to search and interprets what came back.",
     "Kept, and the boundary held under pressure: when order-4 islands yielded nothing (exact "
     "order-4 b rarely solvable over dyadic A), the fix was a projection fallback in the "
     "optimizer, not more LLM. The outer loop grew: directives every N cycles with reuse "
     "between, a plan-usage cap, model-proposed hypotheses, and a web literature loop feeding "
     "every prompt."),
    ("Search/held-out split, enforced structurally",
     "The optimizer has no code path that reads HELDOUT_SET; the held-out gap is a first-class "
     "dashboard metric so it cannot rot unnoticed.",
     "Kept literally: a test walks the optimizer's import graph and fails on any load of the "
     "name. The D5 drill — deliberately feeding the optimizer the held-out set — collapses the "
     "gap to zero and restores it on revert, proving the metric measures what it claims. The "
     "gap is also the honest headline so far: search error transfers poorly to held-out."),
    ("MAP-Elites, one grid per order",
     "Descriptors are stage count and cycle-cost bucket; a table of results rather than a "
     "single champion.",
     "Kept unchanged; the grids are the spine of the findings site (heatmaps + tables), and "
     "cell incumbency is what tier assignment compares against."),
    ("Equal cycle budget, never equal step size",
     "A 2-stage method gets twice the steps of a 4-stage method for the same cost; equal-h "
     "comparisons are the most common route to a wrong conclusion.",
     "Kept — and it produced the project's most counterintuitive measurement: at equal budget "
     "under floor rounding, Euler's search-set error undercuts rk4's, because the floor bias "
     "per arithmetic term dominates truncation at these step counts."),
    ("Fixed resource limits plus a pause watchdog",
     "Low cpu-shares plus docker pause on contention stays out of the way in ~40 lines; no "
     "dynamic allocation, no GPU.",
     "Kept, grown modestly: the watchdog also pauses on battery (owner's rule), hard-stops on "
     "spend/disk, kills on a stale heartbeat, and pushes the two writable repos from the host. "
     "Thresholds live in config.json rather than in code."),
    ("Credentials outside the container; harness mounted read-only",
     "If the agent can write the verifier, the shortest path to a high score is editing the "
     "scorer. PAT scoped to rk-work and rk-findings; the 403 on rk-harness is an acceptance "
     "test.",
     "Half-kept, half-superseded. The read-only mount and pinned verifier hash stand. The PAT "
     "scoping did not survive contact: the owner's token had contents-write everywhere, and "
     "the handoff's 403 probe passed for the wrong reason (missing Administration permission). "
     "As built, the credential simply never enters the container — a filtered env file plus "
     "host-side pushes — which makes the guarantee independent of token scope; the scope probe "
     "is kept as an advisory check."),
    ("Auto-publish numbers, never claims",
     "The site emits values with mechanically-assigned tiers; a wrong result should be a wrong "
     "number in a table, not a claim requiring retraction.",
     "Amended by the owner, with the guard intact: the findings site now also publishes "
     "model-written interpretation and web-researched literature digests — clearly labelled, "
     "and passed through a softener that replaces priority-claim words before storage. The "
     "banned-words guard still hard-fails any page it doesn't like, and it proved itself by "
     "blocking builds over a hypothesis containing 'beats' until the softener existed."),
    ("The encourager may change direction but not stop",
     "Before the calendar date it can only redirect, widen, hypothesize, or advance phase; "
     "set-and-forget systems without a calendar run until the operator gets bored.",
     "Kept: PACKAGE (re-verify everything, no new directions) opens 2026-11-20 and FREEZE "
     "2026-12-05, property-tested over a thousand random states and exercised through the real "
     "clock path."),
    ("Falsification experiment first",
     "If coefficient arithmetic is swamped by derivative evaluation the thesis is dead; find "
     "out in week one, not month three.",
     "Kept, run, recorded either-way as promised: proceed for rk4 on both counts; heun2 under "
     "the slow model sits at 14.8%, a hair under the 15% line, so the verdict is stored as "
     "'mixed' rather than rounded up."),
]

CUTS = """
<p>Adaptive step size and Newton-iteration implicit methods break the execution-time
certificate hard real-time requires — wrong for the target, not merely unaffordable. Order &gt; 4
and linear multistep multiply the space with no reason to expect a larger quantisation effect.
Rosenbrock methods remain the natural second project. One addition to the cut list from the
build: alternative rounding modes (round-to-nearest, stochastic rounding) are deliberately a
<em>measured comparison</em> on the results page, not a search dimension — changing the
arithmetic changes every score in the archive, so it is pinned by the verifier hash.</p>
"""

PRIOR_ART = """
<p>RKTK (Zhang, 2019) already performs unstructured numerical search over Butcher order
conditions and holds an order-10 stage-count record; numerical tableau search is not the
contribution. That line optimises order, stages and error constants in exact arithmetic.
Nobody prices coefficients against a hardware cost model, and nobody evaluates end-to-end in
fixed point — that is the gap, and it is narrow enough to finish. The literature loop keeps
collecting adjacent work (fixed-point ODE solvers, CSD constant multiplication, rounding-error
analysis) into the findings site's literature page as the run proceeds.</p>
"""
