"""Long-form prose for the rk-overview pages. Kept separate from the chart machinery.

This is the owner's explainer repo: unlike rk-findings (auto-generated, numbers only),
these pages carry interpretation and architecture narrative, drafted with Claude and
maintained by the owner. rk-findings stays the machine-truth; anything here that
disagrees with it is wrong here.
"""

ABOUT_NOTE = (
    "rk-overview is the human-maintained explainer for the rk project. The companion site "
    "rk-findings is generated by the harness every cycle and carries the authoritative numbers; "
    "a frozen copy from {date} (US Central) is snapshotted under this site. Drafted with Claude, "
    "edited and owned by the author.")

INTRO = """
<p>The <strong>rk project</strong> is an unattended, months-long search for explicit
Runge&ndash;Kutta tableaus that minimise <em>end-to-end error in Q15 fixed-point arithmetic at a
fixed cycle budget on Cortex-M0+</em> &mdash; instead of the textbook criterion, truncation error
in exact real arithmetic.</p>

<p>The falsifiable claim: classical tableaus were derived assuming exact arithmetic. On an
FPU-less microcontroller in Q15, at step sizes a real controller would use, roundoff dominates
truncation &mdash; so the classically optimal coefficients are not the practically optimal ones,
and nobody has searched the gap between. Prior work (RKTK and its line) searches tableaus
numerically for order and error constants; it does not price coefficients against a hardware
cost model, and it does not evaluate in fixed point. That narrow gap is the project.</p>

<p>Three repositories with three trust levels do the work: <code>rk-harness</code> holds the
verifier, evaluator and cost models and is mounted <em>read-only</em> into the run container;
<code>rk-work</code> accumulates the append-only archive of every verified tableau;
<code>rk-findings</code> receives an auto-generated site of numbers each cycle. This site,
<code>rk-overview</code>, is the human layer on top.</p>
"""

HEADLINES = """
<p>Everything below was measured by the harness; the findings snapshot carries the full tables.</p>
<ul>
<li><strong>The anchor result.</strong> rk4 and rk38 are both 4-stage order-4 methods with the
same stability polynomial. Under a 1-cycle multiplier rk4 is cheaper (33 vs 36 cycles/step);
under a 32-cycle multiplier rk38 is cheaper (64 vs 85). Which method to ship depends on which
multiplier the chip shipped with &mdash; the thesis demonstrated in two textbook methods.</li>
<li><strong>A proof, not a search, at order 2.</strong> The 2-stage order-2 family admits exactly
16 exactly-representable points (a21 = m/2^s, s &le; 6). Exhaustive enumeration shows
<code>midpoint</code> is the cheapest at 11 slow cycles &mdash; optimal within that space, with
<code>heun2</code> two cycles behind. A neighbouring point, a21 = -1/4 with b = (3, -2), has the
better held-out error at 16 cycles.</li>
<li><strong>Roundoff dominates where it matters.</strong> The day-one falsification experiment:
rk4 spends 56% of its cycles on coefficient arithmetic under the fast multiplier (36% under the
slow one), and its Q15 error stops improving below h &asymp; 0.16 on the damped oscillator while
float64 keeps falling &mdash; the roundoff/truncation crossover sits squarely in the practical
range, so the project proceeds.</li>
<li><strong>Floor rounding changes the answers.</strong> Q15 multiplies floor toward negative
infinity (that is what ARM's <code>ASRS</code> does), and the resulting -&frac12;-LSB bias per
term is the same order as the per-step dynamics at these budgets: at equal cycle budget Euler's
<em>search-set</em> error undercuts rk4's, and the stiff <code>rc_thermal</code> problem
collapses toward zero for every method. Swap floor for round-to-nearest and the ordering flips
&mdash; see the rounding chart on the results page.</li>
</ul>
"""

ARCH_SECTIONS = """
<h2>Trust boundaries</h2>
<p>The design assumes the searching agent will, if permitted, optimise the scorer instead of the
score. Four boundaries make that unprofitable:</p>
<ul>
<li><strong>The scorer cannot be edited.</strong> <code>rk-harness</code> is mounted read-only
into the container, and the container refuses to start unless the sha256 over the ten verifier
files (coeffrep, orderconditions, verifier, costmodel, evaluator, problems, and the four fixture
files) matches a pinned value. Every archive record carries the verifier hash that scored it.</li>
<li><strong>No credential reaches the agent.</strong> The GitHub token stays on the host: the
container receives a filtered environment, only ever <em>commits</em> into the mounted
checkouts, and the host watchdog pushes with the owner's own credentials.</li>
<li><strong>The model never grades itself.</strong> Confidence tiers
(heldout_verified / search_only / unreplicated) and hypothesis verdicts
(supported / refuted / inconclusive) are computed by code from the archive. The tier strings do
not appear in any LLM prompt template; a directive carrying an unknown key &mdash; including a
tier &mdash; is rejected, not ignored.</li>
<li><strong>Model-written code is quarantined.</strong> A model-authored problem executes only
after an AST-checked import allowlist (math only, no dunders, no I/O), determinism and time
bounds, a range check, a reference solution, and a promotion gate; it can then join only the
held-out set, so the optimiser can never be steered toward a problem the model invented.</li>
</ul>

<h2>The cycle loop</h2>
<p>The runner executes one idempotent cycle at a time; a crash at any point costs at most one
cycle because the archive is append-only with fsync, state is written atomically, and replay
discards a torn trailing line. Each cycle: replay the archive &rarr; ask the encourager for an
action &rarr; produce candidates &rarr; verify each &rarr; evaluate in Q15 under three cost
models at equal cycle budget &rarr; assign a tier against the cell's incumbent &rarr; append
&rarr; resolve open hypotheses &rarr; regenerate the findings site &rarr; commit &rarr; save
state.</p>

<h2>Verification, in order</h2>
<p>Nine checks, cheap before expensive, all pure code: NOT_EXPLICIT, ROW_SUM_INCONSISTENT,
DYADIC_IMPOSSIBLE (order &ge; 3 with all-dyadic coefficients is provably empty &mdash; the
order-3 condition sums to 1/3, which no dyadic rational equals), ORDER_NOT_MET (exact rational
residuals over rooted trees, never floats), COEFF_UNREPRESENTABLE (a range check &mdash;
inexactness like 1/3 is <em>recorded</em>, never rejected), Q15_OVERFLOW (2&times; amplitude
margin), UNSTABLE, NO_ASYMPTOTIC_WINDOW (the measured-order fit found no consistent slope run),
NAN_OR_INF. Only the primary cost model's columns gate verification; the slow and AVR columns
are archive breadth.</p>

<h2>Arithmetic, exactly</h2>
<p>States are Q15 (int16, scale 2<sup>-15</sup>). A multiply is <code>(a*b) &gt;&gt; 15</code>
with an arithmetic shift &mdash; flooring toward negative infinity, matching ASRS and
deliberately not matching C's truncation. Addition overflow raises rather than wraps, so
overflow becomes a verifier rejection instead of a silent wrong answer. Coefficients are not Q15:
each is an integer-and-shift pair m/2<sup>s</sup> (rk4's 1 and kutta3's 2 do not fit [-1, 1)),
and inexact representations contribute a recorded quantisation error. Cost is driven by CSD
(non-adjacent-form) weight &mdash; 3/8 is dyadic yet costs two shifts and an add &mdash; with
every coefficient priced at min(shift-add expansion, multiply).</p>

<h2>Where candidates come from</h2>
<p>Phase 0 and 1 are exhaustive enumerations (16 points at order 2; 5,094 exact 3-stage order-3
points), so their results are proofs of optimality within the enumerated space, and the site
labels them that way. Phases 2 and 3 run CMA-ES islands over the strictly-lower triangle of A
snapped to dyadics, with b then solved <em>exactly</em> over the rationals from the b-linear
order conditions &mdash; snapping b would make order &ge; 3 impossible by the dyadic theorem.
When the requested order is not exactly solvable for a snapped A (order 4 rarely is), the
projection falls back to the highest solvable order &ge; 2 and the candidate is verified at the
order it actually achieves.</p>

<h2>The outer loop: a research partner, not a sampler</h2>
<p>The LLM (Codex, plan-billed, authenticated on the host and mounted read-only) never touches
the inner loop. It emits JSON directives that can only narrow the search &mdash; target order,
stage counts, structural constraints &mdash; validated against a schema where unknown keys are
rejections. Directives are requested every few cycles (and on every escalation) and reused in
between; calls stop at a plan-usage cap. On HYPOTHESIZE escalations it proposes falsifiable
hypotheses whose ids and verdicts are assigned by code and whose predicates must parse under a
closed grammar (a hand-written parser; no eval anywhere near model output). A literature loop
web-searches a rotating topic every ~50 cycles and feeds the digest into every prompt, so the
directives and hypotheses are grounded in existing research. The digests and the model's prose
interpretation are published on the findings site, clearly labelled and softened so the site's
banned-words guard holds.</p>

<h2>The host layer</h2>
<p>A PowerShell watchdog polls every 10 s: stale heartbeat &rarr; kill; spend over cap or disk
under 5 GB &rarr; stop; laptop on battery or foreground CPU load &rarr; pause (and resume);
plus the host-side pushes. Operational knobs &mdash; container resources, auto-stop after N
minutes/cycles, LLM throttles, watchdog thresholds &mdash; live in a workspace
<code>config.json</code> edited by <code>configure.py</code>; scientific thresholds are
deliberately not configurable because changing them invalidates the archive. A read-only watcher
window renders the whole state live; Ctrl+C in it cannot touch the run.</p>

<h2>What the pre-flight actually caught</h2>
<p>The checklist was executed as a program, not a document, and it earned its keep: the crash
-recovery drill exposed that a runner killed mid-seeding never finished writing the classical
baselines (fixed: seeding is idempotent per hash, every cycle); the trust-boundary probe showed
the original PAT could push the verifier repo despite the handoff's 403 test passing (fixed by
moving the credential out of the container entirely); the first live archive build tripped the
banned-words guard on a hypothesis containing "beats" &mdash; the guard doing
exactly its job against text nobody reviewed.</p>
"""

METHODOLOGY = """
<p>This page is the human account of how the harness works and how it was validated. Its
machine-generated counterpart is the findings site's methodology page — rebuilt by the harness
every cycle, always current on constants and thresholds — available in the
<a href="findings/methodology.html">snapshot here</a> and
<a href="https://jgoetzmann.github.io/rk-findings/methodology.html">live on rk-findings</a>.
That page states what the numbers mean; this one explains why the machinery around them is
built the way it is, and what was actually exercised before the run was left alone. The system
itself is drawn on the <a href="architecture.html">architecture page</a>; the paper trail of
choices is on <a href="design-decisions.html">design decisions</a>.</p>

<h2>The shape of the problem</h2>
<p>An unattended search, partly steered by a language model, produces numbers for months with
nobody watching. Numbers from such a system are worth exactly as much as the guarantees around
them: that the scoring rules could not drift, that the searching process could not touch its
own scorer, and that a crash or a stray operator cannot silently corrupt the record. So the
validation story is really three gates, engaged in order: once at container start, once
inside every cycle, and continuously from the host.</p>

<h2>The gate at container start</h2>
<p>The container's entrypoint refuses to run science before proving its environment, in a fixed
order. It writes a heartbeat immediately — the gate takes long enough that the host watchdog
once killed a fresh container fourteen seconds after start, because the heartbeat file on disk
predated the restart; the fix is the very first line of the entrypoint, not a longer timeout.
It then probes its own mount: if <code>/harness</code> accepts a write, the container exits
rather than run with a writable scorer. It recomputes the verifier hash and compares it to the
pinned value. Finally it runs the golden and canary tests — G1 through G20 plus the K1 and K2
canaries, 55 cases at the pre-flight run — with pytest, against the harness as mounted. Any
failure is exit 1 and the runner never starts.</p>
<p>The point of running tests at start rather than at build time: "the tests passed when the
image was built" claims nothing about the harness that is mounted today. The gate re-earns the
claim on every start, including every automatic restart after a kill.</p>

<h2>Ten files, one hash</h2>
<p>Six modules decide every score: coefficient representation, the order conditions, the
verifier, the cost model, the evaluator, and the problem set. Four fixture files pin their
golden values. A sha256 over those ten files, concatenated in a fixed order, is pinned in
<code>VERIFIER_HASH</code>; the entrypoint recomputes and compares it, and every archive record
stores the hash that scored it. A change to any byte of the ten is therefore loud twice over:
the container refuses to start, and a record produced under a different hash would advertise
the fact in its own row.</p>
<p>This was drilled, not assumed. Pre-flight item A3 altered one line of
<code>coeffrep.py</code> and started the container: exit 1, "VERIFIER HASH MISMATCH — refusing
to run". Restored, the same container gated green and started, the 55 golden and canary cases
passing in under four seconds.</p>

<h2>What the container cannot reach</h2>
<p>The harness mount is read-only (<code>:ro</code> on the docker command line, re-checked by
the entrypoint's write probe). The GitHub credential never enters the container at all: the
env file the container receives is filtered on the host and drops every
<code>GITHUB_TOKEN</code> line, the runner only ever commits into the mounted work and findings
checkouts, and the host watchdog pushes those commits with the owner's own credentials every
ten minutes. The Codex OAuth file is mounted read-only for the plan-billed planning calls.</p>
<p>The original design scoped a token instead: push rights on rk-work and rk-findings, with a
403 on rk-harness as an acceptance test. That plan failed honestly. The pre-flight scope probe
showed the owner's actual token could push the verifier repo, and the earlier 403 had passed
for an unrelated reason. Moving the credential out of the container entirely makes the
guarantee independent of anyone's permission model — there is no token whose scope can rot.
The full story is under <a href="design-decisions.html#credentials">credentials outside the
container</a>.</p>

<h2>The test suites, tiered</h2>
<p>The suite is organised as numbered tiers that mirror the dependency stack, cheapest and
most foundational at the bottom: T1 covers fixed point, coefficient representation and cycle
counting; T2 the order conditions, evaluator and verifier; T3 the archive, search and
directive validation; T4 the ledger, runner and site generator; T5 the operational config and
the watch view; T6 the Central-time display formatting. Together they collect a bit under a
thousand parametrised cases at this snapshot, with a <code>slow</code> marker separating the
second-scale ones.</p>
<p>Two kinds of test carry most of the weight. Golden tests (G-numbered) pin behaviour to
fixture values written down before the build: the measured order of rk4 comes out 4.0706 from
3 fit points, the hand-counted ARMv6-M multiply sequence costs 13 cycles fast and 75 slow, and
the eleven coefficient representations in the fixture reproduce bit for bit. Canary tests
(K-numbered) are anti-gaming: K1 plants a candidate tuned on the search set and asserts it can
earn search_only but never heldout_verified; K2 asserts that a winner in a single problem
family that is worse on both aggregates stays unreplicated. The gate at container start is a
selection from this same suite, so the anti-gaming properties are re-proved on the mounted
code every time the container comes up.</p>

<h2>The pre-flight, executed as a program</h2>
<p>The pre-flight checklist (docs/REVIEW.md in the harness repo) is not a document anyone
initials; <code>scripts/preflight.py</code> executes every machine-checkable item, prints the
measured value next to each verdict, and writes the report with a sign-off block
(docs/REVIEW-REPORT.md). Statuses are PASS, FAIL, MANUAL (needs the host, hardware, or a
human), SKIP and INFO; the trust boundary (A), ground truth (B), anchor result (C) and
falsification (K) sections gate, and a FAIL there is a nonzero exit. The full run, suite and
docker drills included, was executed on 2026-08-30: every gating section green, with eight
items that need the host, hardware or a human left marked MANUAL, each carrying its
instructions in the report.</p>
<p>The drills are where the exercise paid for itself, because they act instead of asserting:
A1 actually tries to write <code>/harness</code> from inside a running container; A3 actually
tampers with a verifier file and expects the refusal; D5 deliberately feeds the optimizer the
held-out set and checks the search/held-out gap collapses to zero, then returns on revert —
which is what shows the gap metric measures what it claims. Three of these drills changed the
system before the run started; that story is told on the
<a href="architecture.html">architecture page</a>.</p>

<h2>The operational layer</h2>
<p>Once running, the container answers to a host watchdog that polls every ten seconds and
holds every kill switch outside the container. A heartbeat older than two minutes is a
<code>docker kill</code>; a wrongful kill self-heals, because the restart policy brings the
container back and the start gate re-runs. Spend over the monthly cap, or free disk under five
gigabytes, is a stop that stays down. The laptop on battery is a pause, plugged back in an
unpause; another foreground workload holding the CPU above 50% for thirty seconds is a pause,
back under 30% an unpause. Pause is atomic, so the run resumes mid-cycle exactly where it
stopped.</p>
<p>The run also throttles itself. Auto-stop limits (wall-clock minutes or cycle count) end the
run at the next cycle boundary. The language model is asked for a fresh directive every five
cycles and on every escalation, with the last directive reused in between; calls stop once
Codex reports 80% of the weekly plan used; the web literature digest runs every fifty cycles
and the archive interpretation every twenty-five. All of these are operational knobs in a
workspace config.json edited through <code>configure.py</code>. Scientific thresholds are
deliberately not in that file: changing them would invalidate the archive, which is why they
live in the hash-pinned code instead.</p>
<p>One bookkeeping rule ties the layer together: everything stored — archive records, events,
heartbeat, run state — is UTC, and only human-facing display converts to US Central, through
one small module. The watchdog's staleness arithmetic and the archive's determinism both
depend on storage never carrying a local time.</p>

<h2>What this page does not cover</h2>
<p>The scientific method of the search itself — the nine verifier checks in order, exact
rational order conditions, equal-cycle-budget evaluation, tier assignment, the encourager
ladder — is on the <a href="architecture.html">architecture page</a>, and the current
constants and thresholds are on the findings methodology page
(<a href="findings/methodology.html">snapshot</a>,
<a href="https://jgoetzmann.github.io/rk-findings/methodology.html">live</a>). The findings
site is the machine truth; if this page and that one ever disagree, trust that one.</p>
"""

# --------------------------------------------------------------------- "how to read this"
# Short expandable explainers rendered under each diagram, chart and table. HTML paragraphs.

HOW_SYSTEM = """
<p>Three columns, left to right: the Windows host, the docker container, and the services the
run talks to. On the host, the watchdog is the only process holding push credentials, and the
config trio (config.json, configure.py, the watcher window) is how the owner steers without
touching the run. Inside the container, the highlighted box is <code>rk-harness</code>:
mounted read-only, hash-checked at start, home of every rule that decides a score. The runner
drives the cycle loop and is the only component that calls the LLM; search produces
candidates; <code>rk-work</code> is the one writable mount. On the right, Codex receives
throttled planning calls, rk-findings receives a commit each cycle, and GitHub Pages deploys
whatever the host pushed.</p>
<p>The arrows carry the trust story: "docker run" is all the host does to start the science,
the container's only writes go into the mounted work checkout, and no arrow carries a GitHub
credential into the middle column.</p>
"""

HOW_CYCLE = """
<p>Ten stages, left to right, top row then bottom. "replay" rebuilds all state from the
append-only archive, which is what lets the loop be killed anywhere. "encourager" picks the
cycle's action from the stall ladder and the calendar. "candidates" come from enumeration
(phases 0 and 1) or CMA-ES islands (phases 2 and 3). The highlighted "verify ×9" is the
nine-check gate, cheap checks before expensive ones. "evaluate" runs survivors in Q15 under
three cost models at equal cycle budget; "tier" compares against the cell's incumbent;
"append" fsyncs the record into the archive; "ledger" resolves hypothesis verdicts by code;
"site" regenerates rk-findings behind the banned-words guard; "commit" happens inside the
container, and the host pushes later.</p>
<p>A crash between any two boxes loses at most the current cycle: nothing before "append" has
side effects, and everything after it can be regenerated from the archive.</p>
"""

HOW_RECORDS = """
<p>The x axis is the cycle number; the y axis is the running total of archive records, meaning
every candidate that passed all nine verifier checks and was appended. Rejected candidates
never appear here (they are counted in the rejection chart). Steep stretches are the
exhaustive phases, where hundreds of enumerated points get verified per cycle; near-flat
stretches are CMA-ES territory, where most sampled tableaus fail a check and the archive grows
by survivors only.</p>
"""

HOW_TIERS = """
<p>One bar per confidence tier. The tier is assigned by code the moment a record is appended,
by comparison with the incumbent of its cell: <em>heldout_verified</em> means better than the
incumbent on the search aggregate and the held-out aggregate, with improvement in at least two
problem families; <em>search_only</em> means better on search but not on held-out, the
signature of overfitting to the search set; <em>unreplicated</em> is everything else,
including every record that lands in an empty cell. No model output touches the assignment,
and the tier strings never appear in an LLM prompt.</p>
"""

HOW_REJECTS = """
<p>One bar per verifier rejection code, counted over the whole event stream. The nine checks
run in a fixed cheap-to-expensive order and stop at the earliest failure, so each rejected
candidate is counted once, under the check that killed it. The mix is dominated by the
expensive tail — NO_ASYMPTOTIC_WINDOW (the measured-order fit found no consistent slope run)
and Q15_OVERFLOW (the trajectory left the 2× amplitude margin) — because the cheap structural
failures mostly cannot occur by construction: enumeration emits only valid points, and the
CMA-ES projection solves b exactly so the order conditions already hold. A rejection has no
side effects; it never enters the archive.</p>
"""

HOW_ROUNDING = """
<p>Four groups, one per classical method. Within each group the blue bar is the error under
floor rounding (what ARM's ASRS instruction does, and what the harness measures everywhere)
and the orange bar is the same measurement rerun with round-to-nearest. Bar height is the RMS
of final-state error over the three search-set problems, every method given the same
65,536-cycle budget under the fast multiplier, so a cheap method takes more, smaller steps.
Compare the two bars within a group to see what rounding costs a method; compare blue bars
across groups to see the ranking the harness actually reports.</p>
<p>Why it matters: floor injects a bias of half an LSB per multiply, always in the same
direction, and at these step counts that bias accumulates faster than truncation error
shrinks. That is how euler's blue bar ends up below rk4's. Round-to-nearest is a
counterfactual measured outside the archive: the rounding mode is part of the pinned
arithmetic, so it is compared here rather than searched over.</p>
"""

HOW_PHASE0 = """
<p>Each row is one of the sixteen 2-stage order-2 tableaus whose coefficients are exactly
representable (a21 = m/2<sup>s</sup> with s &le; 6, and both b weights exact dyadics). a21
fixes everything else: the order conditions force b = (1 &minus; 1/(2&middot;a21),
1/(2&middot;a21)) and c = (0, a21). "slow cycles" is the static per-step cost under the
32-cycle multiplier model, which is the sort key. "held-out error" is the archived end-to-end
Q15 error on the held-out problems at equal cycle budget. The tier badge is the record's
mechanically assigned confidence tier, and the last column names the point when it coincides
with a textbook method. Click any row for the full archived score vector.</p>
"""

HOW_SWEEPS = """
<p>One panel per classical method, from the day-one falsification run, all on the damped
oscillator. Both axes are logarithmic: step size h on the x axis (smaller steps to the left),
final-state error on the y axis. The blue line is Q15 fixed point; the orange line is float64
taking exactly the same steps, so the gap between them is pure arithmetic. Where the orange
line keeps falling as h shrinks but the blue line flattens, roundoff has taken over from
truncation; the dashed vertical marks that crossover. The project's premise lives in that flat
region sitting inside the practical step-size range.</p>
"""

HOW_DECISIONS = """
<p>Each card is one decision from DESIGN.md, written before any code existed. "Original"
condenses what the design said; "As built" records what the working system does today. The tag
is assigned mechanically: "revised in build" appears when the as-built text admits the plan
changed (it contains "superseded", "amended" or "changed"), "held up" otherwise. Two of the
fourteen were revised; the rest survived contact with the build. Every card has a stable
anchor, so a link like <code>design-decisions.html#credentials</code> lands on the exact
decision.</p>
"""

# (anchor_slug, title, original_summary, as_built) — original_summary condensed from DESIGN.md;
# as_built annotates what the code actually does today. Slugs are deep-link anchors: stable,
# short, never reused.
DECISIONS = [
    ("quantization",
     "The problem is quantization, not coefficient prettiness",
     "In floating point, h·b constant-folds and 1/3 costs the same as 0.25; the premise only "
     "survives in fixed point on an FPU-less MCU, where a power-of-two coefficient becomes a "
     "shift. Scope narrowed accordingly.",
     "Kept, and measured: the falsification run puts coefficient arithmetic at 56% of rk4's "
     "cycles under the fast multiplier (36% slow) with a roundoff/truncation crossover at "
     "h ≈ 0.16 on the damped oscillator — comfortably above the 15% kill line."),
    ("dyadic-theorem",
     "Order ≥ 3 admits no all-dyadic tableau",
     "Dyadic rationals are closed under + and ×; Σ b·c² = 1/3 is not dyadic. The objective is "
     "minimising non-dyadic multiplies subject to order, encoded as reject code "
     "DYADIC_IMPOSSIBLE so the search never wastes a cycle on an empty region.",
     "Kept — and it shaped the search space itself: A is snapped to dyadics but b is solved "
     "exactly over the rationals from the b-linear order conditions, because snapping b would "
     "run into this very theorem. The verifier rejects all-dyadic order-3 claims without "
     "evaluating them (tests V5–V7)."),
    ("static-counting",
     "Static cycle counting, not simulation, not hardware",
     "The inner loop is branchless straight-line code, so summing ISA cycle costs gives an "
     "exact count and a genuine WCET figure; host contention cannot corrupt the metric.",
     "Kept, sharpened: the count is fully analytic from the tableau (no compiler or "
     "disassembly in the loop). The model is anchored to hardware by one hand-counted ARMv6-M "
     "sequence (13 cycles fast / 75 slow) that a test reproduces exactly, and emit_c exists "
     "for a one-time human cross-check."),
    ("targets",
     "Cortex-M0+ primary; AVR advisory; two M0+ multiplier variants",
     "M0+ has no FPU/divide/long-multiply, so fixed point is forced; running a 1-cycle and a "
     "32-cycle multiplier model costs nothing and turns hardware-aware into a demonstrated "
     "effect if the ranking changes.",
     "Kept — the ranking does change (rk4 33 vs rk38 36 fast; rk38 64 vs rk4 85 slow). AVR "
     "stays advisory in a stronger sense than planned: after a live candidate was rejected on "
     "an AVR-column infinity, verification was restricted to primary-model columns only; the "
     "slow/AVR numbers are archive breadth."),
    ("q15-overflow",
     "Q15, wrapping semantics, overflow as a rejection",
     "Q31 must be synthesized on M0+; saturation costs a compare-and-branch and destroys exact "
     "counting. Overflow at 2× amplitude is a verifier rejection — a property of the method, "
     "not a runtime cost.",
     "Kept, with one addition the spec missed: rc_thermal's derivative (−11 at t=0) times its "
     "state scale exceeds Q15, so derivatives carry a per-problem power-of-two scale "
     "(DERIV_SCALE, 1/8 there) undone in the step via h. Floor rounding turned out to be a "
     "first-class experimental variable — see the rounding chart."),
    ("inner-outer",
     "Classical optimizer in the inner loop, LLM in the outer loop",
     "A 6-parameter space has gradients; CMA-ES beats an LLM mutation operator for free. The "
     "LLM decides what to search and interprets what came back.",
     "Kept, and the boundary held under pressure: when order-4 islands yielded nothing (exact "
     "order-4 b rarely solvable over dyadic A), the fix was a projection fallback in the "
     "optimizer, not more LLM. The outer loop grew: directives every N cycles with reuse "
     "between, a plan-usage cap, model-proposed hypotheses, and a web literature loop feeding "
     "every prompt."),
    ("heldout-split",
     "Search/held-out split, enforced structurally",
     "The optimizer has no code path that reads HELDOUT_SET; the held-out gap is a first-class "
     "dashboard metric so it cannot rot unnoticed.",
     "Kept literally: a test walks the optimizer's import graph and fails on any load of the "
     "name. The D5 drill — deliberately feeding the optimizer the held-out set — collapses the "
     "gap to zero and restores it on revert, so the metric measures what it claims to. The "
     "gap is also the honest headline so far: search error transfers poorly to held-out."),
    ("map-elites",
     "MAP-Elites, one grid per order",
     "Descriptors are stage count and cycle-cost bucket; a table of results rather than a "
     "single champion.",
     "Kept unchanged; the grids are the spine of the findings site (heatmaps + tables), and "
     "cell incumbency is what tier assignment compares against."),
    ("equal-budget",
     "Equal cycle budget, never equal step size",
     "A 2-stage method gets twice the steps of a 4-stage method for the same cost; equal-h "
     "comparisons are the most common route to a wrong conclusion.",
     "Kept — and it produced the project's most counterintuitive measurement: at equal budget "
     "under floor rounding, Euler's search-set error undercuts rk4's, because the floor bias "
     "per arithmetic term dominates truncation at these step counts."),
    ("resource-limits",
     "Fixed resource limits plus a pause watchdog",
     "Low cpu-shares plus docker pause on contention stays out of the way in ~40 lines; no "
     "dynamic allocation, no GPU.",
     "Kept, grown modestly: the watchdog also pauses on battery (owner's rule), hard-stops on "
     "spend/disk, kills on a stale heartbeat, and pushes the two writable repos from the host. "
     "Thresholds live in config.json rather than in code."),
    ("credentials",
     "Credentials outside the container; harness mounted read-only",
     "If the agent can write the verifier, the shortest path to a high score is editing the "
     "scorer. PAT scoped to rk-work and rk-findings; the 403 on rk-harness is an acceptance "
     "test.",
     "Half-kept, half-superseded. The read-only mount and pinned verifier hash stand. The PAT "
     "scoping did not survive contact: the owner's token had contents-write everywhere, and "
     "the handoff's 403 probe passed for the wrong reason (missing Administration permission). "
     "As built, the credential simply never enters the container — a filtered env file plus "
     "host-side pushes — which makes the guarantee independent of token scope; the scope probe "
     "is kept as an advisory check."),
    ("numbers-not-claims",
     "Auto-publish numbers, never claims",
     "The site emits values with mechanically-assigned tiers; a wrong result should be a wrong "
     "number in a table, not a claim requiring retraction.",
     "Amended by the owner, with the guard intact: the findings site now also publishes "
     "model-written interpretation and web-researched literature digests — clearly labelled, "
     "and passed through a softener that replaces priority-claim words before storage. The "
     "banned-words guard still hard-fails any page it doesn't like, and it proved itself by "
     "blocking builds over a hypothesis containing 'beats' until the softener existed."),
    ("encourager",
     "The encourager may change direction but not stop",
     "Before the calendar date it can only redirect, widen, hypothesize, or advance phase; "
     "set-and-forget systems without a calendar run until the operator gets bored.",
     "Kept: PACKAGE (re-verify everything, no new directions) opens 2026-11-20 and FREEZE "
     "2026-12-05, property-tested over a thousand random states and exercised through the real "
     "clock path."),
    ("falsification-first",
     "Falsification experiment first",
     "If coefficient arithmetic is swamped by derivative evaluation the thesis is dead; find "
     "out in week one, not month three.",
     "Kept, run, recorded either-way as promised: proceed for rk4 on both counts; heun2 under "
     "the slow model sits at 14.8%, a hair under the 15% line, so the verdict is stored as "
     "'mixed' rather than rounded up."),
]

CUTS = """
<p>Adaptive step size and Newton-iteration implicit methods break the execution-time
certificate hard real-time requires — wrong for the target, not merely unaffordable. Order &gt; 4
and linear multistep multiply the space with no reason to expect a larger quantisation effect.
Rosenbrock methods remain the natural second project. One addition to the cut list from the
build: alternative rounding modes (round-to-nearest, stochastic rounding) are deliberately a
<em>measured comparison</em> on the results page, not a search dimension — changing the
arithmetic changes every score in the archive, so it is pinned by the verifier hash.</p>
"""

PRIOR_ART = """
<p>RKTK (Zhang, 2019) already performs unstructured numerical search over Butcher order
conditions and holds an order-10 stage-count record; numerical tableau search is not the
contribution. That line optimises order, stages and error constants in exact arithmetic.
Nobody prices coefficients against a hardware cost model, and nobody evaluates end-to-end in
fixed point — that is the gap, and it is narrow enough to finish. The literature loop keeps
collecting adjacent work (fixed-point ODE solvers, CSD constant multiplication, rounding-error
analysis) into the findings site's literature page as the run proceeds.</p>
"""
