"""Long-form prose for the rk-overview pages. Kept separate from the chart machinery.

This is the owner's explainer repo: unlike rk-findings (auto-generated, numbers only),
these pages carry interpretation and architecture narrative, drafted with Claude and
maintained by the owner. rk-findings stays the machine-truth; anything here that
disagrees with it is wrong here.

Redundancy policy (one home per fact):
  index            -> teasers and links, the hero numbers, the anchor result
  results          -> the six key findings and the run-level charts
  methodology      -> the method: setup, measurement, protocol, trust, testing
  architecture     -> the technical deep dive: structure, boundaries, arithmetic,
                      cost model, search machinery, archive
  design-decisions -> rationale, cuts, prior art
Where another page needs a fact that lives elsewhere, it links instead of repeating.
"""

# Footer provenance, one quiet line per page. {date} is the snapshot date (US Central).
FOOTER = (
    "Generated by rk-overview/tools/generate.py from the run archive; data snapshot "
    "{date} (US Central). This site is frozen at that date; the live numbers keep "
    "moving on rk-findings. Text drafted with Claude, edited and owned by the author.")

HERO_TITLE = "Searching for Runge–Kutta methods that survive fixed-point arithmetic"

HERO_LEAD = """
<p class="herolead">An unattended, months-long search for explicit Runge&ndash;Kutta
tableaus that minimise <strong>end-to-end error in Q15 fixed point at a fixed cycle budget
on Cortex-M0+</strong> &mdash; not the textbook criterion of truncation error in exact
arithmetic. The search runs inside a container that cannot edit its own scorer, and it has
findings: <a href="results.html">discovered methods cut held-out error up to 3.0&times;
against the best classical anchor</a>, and the mechanism is a half-LSB rounding bias that
reorders the classical field before any search begins.</p>
"""

INTRO = """
<p>The falsifiable claim behind the project: classical tableaus were derived assuming exact
arithmetic. On an FPU-less microcontroller in Q15, at step sizes a real controller would
use, roundoff dominates truncation, so the classically optimal coefficients are not the
practically optimal ones, and nobody had searched the gap between. Prior work (RKTK and its
line) searches tableaus numerically for order and error constants; it does not price
coefficients against a hardware cost model, and it does not evaluate in fixed point. That
narrow gap is the project.</p>

<p>The work is split across four repositories with distinct trust levels; the
<a href="architecture.html">architecture page</a> draws the split and the container
boundary that keeps the searching agent away from its own scorer.</p>
"""

# The anchor result stays on the index: it is the thesis in two textbook methods.
ANCHOR_TEXT = """
<p>rk4 and rk38 are both 4-stage order-4 methods with the same stability polynomial;
textbooks treat them as interchangeable. Priced against real multipliers they are not:
under a 1-cycle multiplier rk4 is cheaper (33 vs 36 cycles per step), under a 32-cycle
multiplier rk38 is cheaper (64 vs 85), because rk4's coefficients cost more shift-add
work. Which method to ship depends on which multiplier the chip shipped with. That is the
project's thesis demonstrated in two methods everyone already knows; the
<a href="results.html">key findings</a> show what a search does with it.</p>
"""

# One-line teasers for the index; slugs must match generate.FINDINGS slugs.
TEASERS = [
    ("efficiency", "Discovered methods beat every classical anchor",
     "13 of 14 discovered grid cells beat all classical anchors of equal or lower cost on "
     "held-out error; the best cuts error 3.0× at the same 65,536-cycle budget."),
    ("floor-flip", "Floor rounding reorders the classical field",
     "Under the hardware's floor rounding, Euler's search-set error undercuts rk4's; "
     "swap in round-to-nearest and the textbook order returns."),
    ("crossover", "Quantization overtakes truncation inside the practical range",
     "rk4's Q15 error decouples from its float error at h = 0.156 on the damped "
     "oscillator, and gets worse as steps shrink."),
    ("rc-thermal", "A stiff problem hits a quantization floor",
     "All eight classical methods land within 1.6% of each other on rc_thermal because "
     "each drives the state to within a few LSBs of zero; the error reported is the "
     "reference itself."),
    ("phase0", "One space closed with a proof",
     "The 16-point 2-stage family was enumerated in full; the optimum is not a textbook "
     "method, and it beats all eight classical anchors."),
    ("validation", "Discovered methods hold up on practical problems",
     "Five equations from real embedded domains, seen by no search and feeding no archive "
     "statistic: the discovered methods carry lower Q15 error on four of the five, median "
     "error ratio 0.475."),
]

# ---------------------------------------------------------------------------- results page

# Scope line printed once at the top of the key findings page, instead of repeating the
# conditions under every figure.
RESULTS_SCOPE = (
    "All numbers on this page share one setting unless a figure says otherwise: total "
    "budget 65,536 cycles, m0plus_fast cost model, Q15 fixed point with floor (ASRS) "
    "rounding, held-out problems. Cheaper methods therefore take more, smaller steps. "
    "Charts are built from tools/key_findings.json, recomputed from the archive; finding 6 "
    "reads rk-work/validation/results.json and uses its own practical problems.")

HEADLINE_VERDICT = """
<p class="verdict">At a fixed budget of 65,536 cycles on a Cortex-M0+ cost model, the
search found Runge&ndash;Kutta methods that cut held-out error by up to
<strong>3.0&times;</strong> against the best classical method, and the data says why:
Q15's floor rounding injects a &minus;&frac12;-LSB bias per multiply that reorders the
classical field before any search begins. The evidence below: an efficiency frontier
where 13 of 14 discovered cells beat every classical anchor of equal or lower cost; a
rounding-mode experiment in which Euler outranks rk4; the measured step size where
quantization noise overtakes truncation error; a stiff problem where every classical
method reports the reference norm as its error; one search space small enough to
close with an exhaustive proof; and a validation suite of five practical problems from
embedded applications, unseen by any search, where the discovered methods carry the
lower error on four.</p>
"""

# Each finding: slug (also the section anchor), title, intro paragraphs (before the
# figure), and interpretation paragraphs (after it). Figure captions live with the chart
# builders in generate.py so caption and geometry stay in one place.
F_EFFICIENCY_INTRO = """
<p>The archive keeps one elite per MAP-Elites cell (order &times; stage count &times;
cycle-cost bucket). At this snapshot the grid has 16 occupied cells: 14 held by discovered
methods, 2 by classicals &mdash; euler owns the only order-1 cell, and rk38 still owns the
4-stage order-4 cell, where no discovered method displaced it. The fair comparison is
against every classical anchor of equal or lower per-step cost, since a cheaper method
could always be substituted; 13 of the 14 discovered cells win that comparison, with a
median error ratio of 0.72 and a best of 0.34.</p>
"""

F_EFFICIENCY_INTERP = """
<p>The one loss is the 17-cycle order-2 cell at 0.0902 against midpoint's 0.0844 (ratio
1.07). The best discovered method is a 3-stage order-2 tableau at 22 cycles per step,
held-out error 0.0286 against 0.0844 for midpoint, the best classical anchor: A =
[[0,0,0], [13/16,0,0], [5/32,11/32,0]], b = (0,0,1), c = (0,13/16,1/2). Every coefficient
is an exact dyadic, so the method costs only shifts and adds; measured order 2.02.
Per-problem it holds up across all four held-out problems: pendulum 0.0047, dc_motor
0.0277, rc_thermal 0.0461, quaternion 0.0191.</p>
<p>Three honest caveats. Cell elites are selected by held-out error among the
archive's 45,000+ candidates, so champion values carry selection bias (the optimizer itself only ever sees
the search-set error). The best cell's tier is "unreplicated"; tiers are mechanical
insertion-time labels against the then-incumbent, not a validation grade, and 5 of the 14
discovered elites are heldout_verified. And classical held-out RMS is floored near 0.078
by the rc_thermal saturation (finding 4), which the discovered winners break; that floor
flatters no one, but it is part of why the classical anchors bunch together.</p>
"""

F_FLIP_INTRO = """
<p>Every Q15 multiply here floors toward negative infinity, because that is what ARM's
<code>ASRS</code> instruction does. Each floored product carries an expected bias of
&minus;&frac12; LSB, always in the same direction. At these budgets that bias accumulates
faster than truncation error shrinks, and it is large enough to reorder the classical
methods. The counterfactual was measured directly: the same four methods, same budget,
same problems, rerun with round-to-nearest.</p>
"""

F_FLIP_INTERP = """
<p>On the three search-set problems, floor puts euler first (RMS 0.0129) and rk4 last
(0.0590, 4.6&times; worse than euler); round-to-nearest restores the textbook order with
rk4 ahead of euler (0.0289 vs 0.0469). Over all seven problems rk38 stays first in both
modes, but floor compresses the field. Per problem, the best method changes on five of
the seven outright; on dahlquist, floor puts three methods in an exact tie, and only
dc_motor keeps the same winner cleanly.</p>
<p>Dahlquist is the clean mechanism case. Under floor, euler, heun2 and rk38 all report
error 4.53999e-05, which <em>is</em> exp(&minus;10), the entire reference value: the Q15
state decays to exactly zero, the true answer is below one LSB, and floor's downward bias
lands on the right answer. Under round-to-nearest the state stalls in a dead zone above
zero and the error is up to 2032&times; worse. The bias is not noise; it is a systematic
force the winning methods exploit.</p>
"""

F_CROSSOVER_INTRO = """
<p>The project's premise was tested before the search started: if truncation error
dominates roundoff at practical step sizes, classical analysis already gives the right
answer and the search is pointless. The falsification run swept step size on the damped
oscillator, computing each method's error twice: in Q15, and in float64 taking exactly the
same steps, so the gap between the curves is pure arithmetic.</p>
"""

F_CROSSOVER_INTERP = """
<p>rk4's float error falls as h<sup>4</sup> to 5.8e-11, while its Q15 error bottoms out
at 1.13e-3 (h = 0.31), decouples from the float curve at h = 0.156, and sits at 2.58e-2
by h = 0.0098: below the crossover, more steps mean more floored multiplies, not more
accuracy. heun2 decouples later, at h = 0.039. Both crossovers sit inside the practical
step-size range, which is what the premise required.</p>
<p>The stored verdict is "mixed", and honestly so: coefficient arithmetic is 50&ndash;56%
of per-step cycles under the fast multiplier (well above the 30% proceed threshold), but
heun2 under the slow multiplier sits at 14.8%, a hair under the 15% kill line. The
budget-level consequence is not mixed: at the shared budget under floor, rk4 wins 0 of 7
problems (euler and rk38 take three each, heun2 one); even under round-to-nearest it wins
only quaternion, with rk38 taking five.</p>
"""

F_RC_INTRO = """
<p>rc_thermal is the archive's stiff problem: a three-state RC network decaying toward
equilibrium, derivative stored at DERIV_SCALE = 1/8, one LSB = 1.22e-4 in physical units.
On it, all eight classical methods report errors between 0.1558 and 0.1582, a spread of
1.6%. That agreement is not convergence; it is collapse.</p>
"""

F_RC_INTERP = """
<p>Each method drives the Q15 state to within 4&ndash;18 LSBs of the origin (euler ends at
raw state (14,15,17), rk4 at (4,4,6)) while the true solution still has norm 0.1592 at
t_end = 4. The reported error is essentially the reference itself. The mechanism is the
floor bias again: late in the decay the scaled derivative terms are a few LSBs, floor
turns them into extra decay, and the state falls to zero instead of tracking the slow
mode.</p>
<p>Two measurements prove it is a floor artifact, not a Q15 limit. Under round-to-nearest,
the same rk38 reaches 0.0511. And the best discovered method reaches 0.0461 <em>while
still using floor</em>: the search found coefficients that keep the state out of the dead
zone under the same arithmetic that kills every classical method. This is also why
classical held-out aggregates are floored near 0.078 in finding 1.</p>
"""

F_PHASE0_INTRO = """
<p>Phase 0 is the one part of the space small enough to close completely: 2-stage methods
with a21 on the dyadic lattice (|a21| &le; 2, denominators to 2<sup>6</sup>), 256 lattice
candidates, of which exactly 16 have exactly representable b weights (the order conditions
force b = (1 &minus; 1/(2a21), 1/(2a21))). All 16 were enumerated, verified and archived;
events.jsonl records the enumeration complete. This is a proof over the space, not a
search result.</p>
"""

F_PHASE0_INTERP = """
<p>The optimum is a21 = &minus;1/8 with b = (5, &minus;4): held-out error 0.0613 at 15
cycles per step, a near-tie with a21 = &minus;1/4 at 0.0614 (0.04% apart; call it a tie).
Both are negative-a21 points no textbook lists, and both beat all eight classical anchors
(best: midpoint at 0.0844). Within the family, midpoint ranks 7th and heun2 12th of 16.
The pattern favours small negative a21: a probe step taken slightly backwards, with a
large-coefficient correction, which under floor rounding partially cancels the accumulated
downward bias.</p>
<p>Every row below expands to the full archived record for that point, including the
per-problem errors and the exact coefficient representations. Rows are ordered
cheapest-first under the 32-cycle multiplier, and the last column names a point when it
coincides with a textbook method.</p>
"""

F_VALIDATION_INTRO = """
<p>Everything above is measured on the archive's own seven problems, so a fair question
remains: do methods selected there transfer to dynamics nobody tuned for? The validation
suite asks that directly, with five equations taken from real embedded application
domains &mdash; an averaged buck converter (power electronics), a Li-ion 2RC battery
equivalent circuit, a linear single-track vehicle model, a type-2 PLL acquiring lock, and
the Bergman glucose minimal model &mdash; none of which any optimizer saw and none of
which feeds any archive statistic. Discovered methods from the live archive and the
classical anchors run each problem at the same 65,536-cycle budget in Q15 with floor
rounding, scored against independent references: closed forms where the systems are
linear, a high-precision integration elsewhere. The protocol is described under
<a href="methodology.html#practical">practical validation</a> on the methodology
page.</p>
"""

F_VALIDATION_INTERP = """
<p>The discovered methods carry the lower error on four of the five problems, with a
median best-discovered to best-classical error ratio of 0.475. The margin runs from
decisive on the buck converter (0.00198 vs 0.0208 for rk38, a 10.5&times; gap) to
moderate on glucose (ratio 0.556). On three of the four wins the winner is the same
3-stage order-2 champion from finding 1, coefficients unchanged; on the vehicle model an
order-4 discovered method wins instead. The fifth problem is the honest miss: on the PLL,
rk38 reaches 0.0128 against the champion's 0.0159 (ratio 1.24), so the transfer is
strong, not universal.</p>
<p>Two checks keep the comparison clean. Float64 runs of the same tableaus at the same
step counts land between 4e-14 and 8e-5 error, in every case hundreds of times below the
Q15 number, so every error above measures quantization &mdash; exactly the regime the
search selects for. And the largest raw Q15 value seen anywhere is 20,130 of the int16
limit 32,767, so no run leaned on overflow luck. Full tables, tableaus, per-problem
provenance and the verbatim verdict line are on the
<a href="https://jgoetzmann.github.io/rk-findings/validation.html">findings validation
page</a>, generated from the same results file.</p>
"""

RUN_CHARTS_INTRO = """
<p>The findings above are states of the archive; these charts are the run that produced
it. All three are computed from the archive and event stream at snapshot time.</p>
"""

# ---------------------------------------------------------------------------- architecture

ARCH_LEAD = """
<p>Four repositories, one container boundary, one loop. This page draws the as-built
system; the <a href="methodology.html">methodology page</a> covers how each boundary was
tested, and <a href="design-decisions.html">design decisions</a> records why each piece is
shaped the way it is.</p>
"""

ARCH_REPOS = """
<p>The split exists so that each artifact has exactly one writer and one trust level.
<code>rk-harness</code> is the scorer: verifier, evaluator, cost models, tests. It enters
the run container read-only, and ten of its files are pinned by a sha256 the container
re-checks at every start. <code>rk-work</code> is the run's state: an append-only archive
of every verified tableau, the event stream, the hypothesis ledger. <code>rk-findings</code>
receives a machine-generated site of numbers, rebuilt by the run every cycle and published
continuously. <code>rk-overview</code> is this site: human-written, regenerated by hand,
and carrying a frozen copy of the findings site from its snapshot date.</p>
"""

ARCH_BOUNDARIES = """
<p>The design assumes the searching agent will, if permitted, optimise the scorer instead
of the score. Four boundaries make that unprofitable:</p>
<ul>
<li><strong>The scorer cannot be edited.</strong> <code>rk-harness</code> is mounted
read-only, and the container refuses to start unless the sha256 over the ten verifier
files matches the pinned value. Every archive record carries the hash that scored it.</li>
<li><strong>No credential reaches the agent.</strong> The GitHub token stays on the host.
The container receives a filtered environment, only ever commits into the mounted
checkouts, and the host watchdog pushes with the owner's own credentials.</li>
<li><strong>The model never grades itself.</strong> Confidence tiers and hypothesis
verdicts are computed by code from the archive. Tier strings appear in no LLM prompt
template, and a directive carrying an unknown key is rejected, not ignored.</li>
<li><strong>Model-written code is quarantined.</strong> A model-authored problem executes
only after an AST-checked import allowlist (math only, no dunders, no I/O), determinism
and time bounds, a range check, a reference solution, and a promotion gate. It can then
join only the held-out set, so the optimiser can never be steered toward a problem the
model invented.</li>
</ul>
"""

ARCH_CYCLE = """
<p>The runner executes one idempotent cycle at a time. A crash at any point costs at most
one cycle: the archive is append-only with fsync, state is written atomically, and replay
discards a torn trailing line.</p>
"""

ARCH_VERIFY = """
<p>Nine checks, cheap before expensive, all pure code. Only the primary cost model's
columns gate verification; the slow and AVR columns are archive breadth.</p>
<ol class="checks">
<li><strong>NOT_EXPLICIT</strong> &mdash; A must be strictly lower triangular.</li>
<li><strong>ROW_SUM_INCONSISTENT</strong> &mdash; c must equal the row sums of A.</li>
<li><strong>DYADIC_IMPOSSIBLE</strong> &mdash; order &ge; 3 with all-dyadic coefficients
is provably empty: the order-3 condition sums to 1/3, which no dyadic rational equals.</li>
<li><strong>ORDER_NOT_MET</strong> &mdash; exact rational residuals over rooted trees,
never floats.</li>
<li><strong>COEFF_UNREPRESENTABLE</strong> &mdash; a range check only; inexactness like
1/3 is recorded, never rejected.</li>
<li><strong>Q15_OVERFLOW</strong> &mdash; the trajectory must hold a 2&times; amplitude
margin.</li>
<li><strong>UNSTABLE</strong> &mdash; the stability interval must be usable.</li>
<li><strong>NO_ASYMPTOTIC_WINDOW</strong> &mdash; the measured-order fit found no
consistent slope run.</li>
<li><strong>NAN_OR_INF</strong> &mdash; any non-finite value anywhere is fatal.</li>
</ol>
"""

ARCH_ARITH = """
<p>States are Q15: int16 at scale 2<sup>&minus;15</sup>. A multiply is
<code>(a*b) &gt;&gt; 15</code> with an arithmetic shift, flooring toward negative
infinity; that matches ARM's ASRS and deliberately does not match C's truncation,
which rounds toward zero. The two conventions disagree on every negative product with
a nonzero remainder (q15_mul(&minus;1, 1) is &minus;1 under floor, 0 under
truncation), and getting this wrong would bias every result in the project, so the
divergence vectors are pinned as fixtures. Nothing saturates and nothing wraps:
operands and results are range-checked, anything outside int16 raises, and the
pipeline turns the exception into a verifier rejection instead of a silent wrong
answer. Skipping saturation mirrors the hardware rather than cutting a corner: M0+
has no SSAT instruction, and saturating in software needs a compare and branch, which
would destroy both branchlessness and exact cycle counting.</p>
<p>Floor rounding is one-sided: the computed product never exceeds the exact product,
and the discarded bits average about half an LSB of deficit per term.
Round-to-nearest would make the per-term error zero-mean and let errors partially
cancel; flooring accumulates the bias in one direction across every coefficient
application and every step. A fixed-step integration at the standard budget performs
thousands of such products, so at small step sizes the drift, not roundoff variance,
dominates Q15 error. The harness keeps the hardware semantics because shipped code on
this target would floor too; the measured consequences are
<a href="results.html#floor-flip">key finding 2</a>.</p>
<p>Coefficients are not Q15. Each is an integer-and-shift pair m/2<sup>s</sup> with
|m| &le; 32767 and 0 &le; s &le; 20 (rk4's 1 and kutta3's 2 do not fit
[&minus;1, 1)), applied as <code>(v*m) &gt;&gt; s</code>. When no exact pair exists,
1/3 for instance, the closest pair is used and the gap is recorded as a quantisation
error: a measured property, never a rejection.</p>
<p>Derivatives get one extra mechanism. The Q15 right-hand side wraps the physical
float64 derivative: state out to physical units, derivative in float64, result scaled
back into Q15. A derivative can be larger than the state it drives; rc_thermal's is
&minus;11 at t = 0, which times the state scale 0.25 leaves Q15 range. Such a problem
stores its derivative with an extra power-of-two factor (DERIV_SCALE = 1/8 there, 1
everywhere else), and the step undoes it by inflating the step-size constant,
h_q = q15(h / DERIV_SCALE). The compensation is exact because both factors are powers
of two.</p>
<p>The Q15 integrator takes n equal steps of the budgeted size. Within a step, each
stage stores h times its derivative (the multiply by h_q happens once, at
evaluation), so applying a coefficient is a single (m, s) multiply-and-add per
nonzero entry, and the b combination works the same way. The simulator tracks the
largest absolute integer seen anywhere in the trajectory, which becomes the overflow
margin, 1 / (2 &middot; max|q| / 32768): above 1.0 exactly when everything stayed
under half of full scale, the 2&times; headroom the verifier demands. A float64 twin
of the integrator exists for the convergence study only and plays no part in scoring
Q15 error.</p>
"""

ARCH_COSTMODEL = """
<p>Costs are counted analytically: no compiler, no emulator, no board in the loop, so
the cycle count is a pure function of the tableau and identical on every machine.
Three models assign cycles to five operation classes:</p>
<div class="scroll"><table>
<thead><tr><th>model</th><th>mul</th><th>add</th><th>shift</th><th>load</th><th>store</th><th>role</th></tr></thead>
<tbody>
<tr><td>m0plus_fast</td><td>1</td><td>1</td><td>1</td><td>2</td><td>2</td><td>M0+ with single-cycle multiplier; primary</td></tr>
<tr><td>m0plus_slow</td><td>32</td><td>1</td><td>1</td><td>2</td><td>2</td><td>M0+ with iterative multiplier; primary</td></tr>
<tr><td>avr_approx</td><td>14</td><td>2</td><td>8</td><td>2</td><td>2</td><td>8-bit AVR approximation; advisory only</td></tr>
</tbody></table></div>
<p>Applying a coefficient (m, s) costs nothing when it is 0 (the term is omitted) or
&plusmn;1 (a copy whose sign folds into the add). Otherwise it costs the cheaper of
two implementations: a shift-add expansion of w shifts plus w &minus; 1 adds, where w
is the CSD weight of m (the minimum number of nonzero signed powers of two in its
non-adjacent form; 3/8 is dyadic yet costs two shifts and an add), or one hardware
multiply plus one shift. Taking the minimum is the point of the model: with a 1-cycle
multiplier the multiply nearly always wins and coefficient structure barely matters,
while with a 32-cycle multiplier the shift-add expansion wins up to about w = 10,
making low-weight coefficients dramatically cheaper. Per stage with any nonzero A
entry, and once more for the b combination, the model charges a load, the coefficient
cost plus an add per nonzero entry, and a store, all times the state count.
Derivative evaluation is excluded: identical across methods at the same stage count,
it only shifts every method by the same constant.</p>
<p>Two cross-checks anchor the model to hardware. A pinned, hand-counted ARMv6-M
assembly sequence must count to exactly 13 cycles under m0plus_fast and 75 under
m0plus_slow, and a reference C emitter can print the step function a compiler would
see, for one-off human comparison; the harness never compiles or executes it. The
rk4-versus-rk38 comparison on the <a href="index.html">overview page</a> is pinned
the same way, as golden test G21: twelve numbers verified before any search ran.</p>
"""

ARCH_CANDIDATES = """
<p>Phases 0 and 1 are exhaustive enumerations (16 points at order 2; 5,094 exact 3-stage
order-3 points), so their results are proofs within the enumerated space, and the site
labels them that way. Phases 2 and 3 run CMA-ES islands over the strictly-lower triangle
of A snapped to dyadics, with b then solved <em>exactly</em> over the rationals from the
b-linear order conditions; snapping b would make order &ge; 3 impossible by the dyadic
theorem. When the requested order is not exactly solvable for a snapped A (order 4 rarely
is), the projection falls back to the highest solvable order &ge; 2 and the candidate is
verified at the order it actually achieves.</p>
<p>The projection, exactly: a CMA-ES sample is s(s&minus;1)/2 free A entries plus s
guesses for b. The A entries snap to the lattice k/D, where D is the directive's
dyadic denominator cap; the abscissae c are then the exact row sums of A. The order
conditions up to the target order, linear in b once A and c are fixed, are assembled
as an exact system over Fractions (one row per rooted tree, right-hand side
1/&gamma;(tree)) and solved by Gaussian elimination over Fractions: determined
components come out as exact rationals, leftover degrees of freedom take the CMA
guess snapped to the same lattice, and an inconsistent system returns no tableau.
Non-dyadic weights like 1/6 survive as exact fractions and are later applied through
their closest (m, s) pair, with the gap recorded as quantisation error.</p>
<p>Around the projection, CMA-ES (initial step size 0.3) minimises the search-set RMS
at the shared budget plus a 1e6 quadratic penalty on the order-condition residuals,
with 1e9 assigned to anything that overflows or cannot be projected; only the three
search problems are reachable from this loop. On stagnation it restarts with a
derived seed (seed + 1000k for restart k), improving tableaus are deduplicated by
content hash, and islands running under different seeds exchange the record with the
lowest held-out error, using scores already computed downstream by the evaluator,
never by the search itself.</p>
<p>The enumerated spaces are lattices, counted before they are walked. Phase 0's one
free parameter runs over 256 dyadic values, of which exactly 16 yield exactly
representable b weights; that space is closed as
<a href="results.html#phase0">key finding 5</a>. Phase 1 parameterises the 3-stage
order-3 family by its two abscissae, each over a 1,024-value lattice: 1,048,576
ordered pairs, well under the module's 100,000,000-candidate cap (past the cap, the
code would fall back to CMA-ES and record that it did). Pairs survive only when the
induced matrix entries and c<sub>2</sub> are exactly representable, every emitted
tableau is asserted to satisfy the order-3 residuals exactly, and 5,094 make it
through.</p>
"""

ARCH_ARCHIVE = """
<p>Every verified candidate becomes one JSON line in a per-day file, appended with
write-then-fsync: the tableau as exact fractions, its sha256 content hash, the full
score vector, the mechanically assigned tier, the cycle id and seed, the verifier
hash in force when it was scored, the directive and hypothesis ids that motivated it,
and a UTC timestamp. Replay validates as it rebuilds: a line that fails JSON parsing
or schema validation is dropped, a record whose stored hash disagrees with its
recomputed tableau hash is rejected, and a tier string outside the closed three-value
set fails validation.</p>
<p>The working structure over the records is MAP-Elites: one grid per symbolic order,
each cell keyed by stage count and a log2 band of the m0plus_fast cycle count (below
16 is bucket 0, 16&ndash;31 is 1, 32&ndash;63 is 2, and so on up to bucket 7 at 1024
and above). Within a cell the elite is the record with strictly the lowest held-out
error; ties and non-finite comparisons keep the earlier record. Replay also maintains
Welford running statistics per (order, stages) cell for each model and metric, which
is what the hypothesis ledger's predicates read. Problems admitted from quarantine
run in shadow for 10 cycles, evaluated and recorded but excluded from tier decisions,
before they count.</p>
"""

ARCH_OUTER = """
<p>The LLM (Codex, plan-billed, authenticated on the host, mounted read-only) never
touches the inner loop. It emits JSON directives that can only narrow the search: target
order, stage counts, structural constraints, validated against a schema where unknown
keys are rejections. Beyond the schema, hand-applied rules bound every field: order 1
to 4, at most three stage counts between 2 and 6, force-zero positions strictly below
the diagonal, a dyadic denominator cap that is a power of two at most 32768, islands 1
to 8, a budget of 5 to 120 minutes, a rationale under 500 characters. A malformed
directive is discarded and logged, and a deterministic fallback searches the emptiest
grid cell instead. Directives are requested every few cycles and on every escalation,
and reused in between; calls stop at a plan-usage cap.</p>
<p>On HYPOTHESIZE escalations it proposes falsifiable hypotheses whose ids and verdicts
are assigned by code and whose predicates must parse under a closed grammar: a
hand-written tokenizer and recursive-descent parser with a 2,000-character cap and a
control-character ban, no eval anywhere near model output (a grep canary enforces
that), and a dunder call is a syntax error, not code. The grammar, in full:</p>
<pre class="grammar">expr    := term (("AND" | "OR") term)*
term    := field op field | field op number
field   := model "." cell "." metric
model   := "fast" | "slow" | "avr_approx"
cell    := "p" digit "s" digit
metric  := "heldout" | "search" | "cycles" | "order"
op      := "&lt;" | "&gt;" | "&lt;=" | "&gt;=" | "=="</pre>
<p>A field such as fast.p3s4.heldout resolves against the archive's cell statistics:
the minimum of the metric over every cycle bucket at that (order, stages), except the
order metric, which uses the mean. How verdicts are then assigned is protocol, not
machinery, and lives on the <a href="methodology.html#protocol">methodology page</a>.
A literature loop web-searches a rotating topic every ~50 cycles and feeds the digest
into every prompt. The digests and the model's prose interpretation are published on
the findings site, clearly labelled and passed through a softener so the site's
banned-words guard holds.</p>
"""

ARCH_HOST = """
<p>A PowerShell watchdog polls every 10 seconds: stale heartbeat &rarr; kill; spend over
cap or disk under 5 GB &rarr; stop; laptop on battery or foreground CPU load &rarr; pause
and resume; plus the host-side pushes. A wrongful kill self-heals, because the restart
policy brings the container back and the start gate re-runs; spend and disk stops stay
down; pause is atomic, so the run resumes mid-cycle exactly where it stopped.
Operational knobs (container resources, auto-stop, LLM throttles, watchdog thresholds)
live in a workspace <code>config.json</code> edited by <code>configure.py</code>.
Scientific thresholds are deliberately not configurable: changing them would invalidate
the archive, so they live in the hash-pinned code. A read-only watcher window renders
the whole state live; Ctrl+C in it cannot touch the run. One bookkeeping rule ties the
layer together: storage is UTC everywhere, and only human-facing display converts to US
Central, through one small module; the watchdog's staleness arithmetic and the
archive's determinism both depend on it.</p>
<p class="note">Three pre-flight drills changed this system before the run started; that
story is on the <a href="methodology.html#preflight">methodology page</a>.</p>
"""

# ---------------------------------------------------------------------------- methodology
# One skeleton, shared with the findings methodology page: experimental setup,
# measurement, statistical protocol (incl. practical validation), verification and
# trust, testing, reproducibility, limitations. Human voice here; the formal version
# is the findings page, the technical depth is architecture.html.

METH_LEAD = """
<p>Numbers from an unattended, partly model-steered search are worth exactly as much as
the method behind them. This page is that method: what the experiment fixes in advance,
what gets measured, how a claim earns a verdict, what stands between the model and the
scorer, and what was tested. The formal version, always current on constants and
thresholds, is the findings methodology page
(<a href="findings/methodology.html">snapshot</a>,
<a href="https://jgoetzmann.github.io/rk-findings/methodology.html">live</a>); the
system internals live on the <a href="architecture.html">architecture page</a>.</p>
"""

METH_SETUP = """
<p>Everything scientific is fixed before the run: explicit Runge&ndash;Kutta tableaus
of orders 1 to 4 and 2 to 6 stages, scored in Q15 fixed point under an analytic
Cortex-M0+ cycle model, at a budget of 65,536 cycles per problem. Methods compete at
equal budget, never equal step size, so a cheap method earns its ranking by taking
more, smaller steps. Seven fixed test problems drive every error number: three the
optimizer sees, four held out to catch overfitting. The split is structural, not a
convention; a test walks the optimizer's import graph and fails on any load of the
held-out set's name.</p>
"""

METH_MEASURE = """
<p>A method's score is the error at the end of each integration: distance to the
reference solution, scaled by the problem's amplitude, or drift in an invariant
(energy for the pendulum, norm for the quaternion). Alongside it the harness measures
the order each tableau actually delivers, fitting error against step size and letting
the data pick the fitting window; rk4 comes out at 4.07, and a broken implementation
reads 2 or 3 instead. Before any of that counts, nine verifier checks gate the
candidate, cheap structural checks ahead of any simulation; the annotated list is on
the <a href="architecture.html">architecture page</a>.</p>
"""

METH_PROTOCOL = """
<p>Confidence is assigned by code at the moment a record is written: heldout_verified,
search_only, or unreplicated, by comparison against the incumbent of the record's grid
cell. The model can propose hypotheses, but only as machine-checkable predicates in a
closed grammar, and it never writes the verdict: cells with no data mean inconclusive,
effects below Cohen's d of 0.2 mean inconclusive, and every refuted hypothesis is fed
back into later prompts so it stays refuted. The project's premise went through the
same discipline: a falsification experiment with kill and proceed thresholds committed
in advance, run before the search started, its verdict ("mixed") published either way
(<a href="results.html#crossover">key finding 3</a>).</p>
"""

METH_PRACTICAL = """
<p>A practical validation suite runs outside the search entirely: equations taken from
real applications, which no optimizer ever saw and no archive statistic includes.
Champions and classical anchors run on them at the same 65,536-cycle budget, under the
same arithmetic and cost model. The point is to ask whether methods selected on the
fixed suite hold up on dynamics nobody tuned for. The outcome is
<a href="results.html#validation">key finding 6</a>; the full tables live on the
<a href="https://jgoetzmann.github.io/rk-findings/validation.html">findings validation
page</a>.</p>
"""

METH_GATE = """
<p>The container refuses to run science before proving its environment, in the fixed
order the diagram shows: heartbeat, a probe that the harness mount rejects writes, the
verifier hash against its pinned value, then the golden and canary tests against the
harness as mounted (55 cases, under four seconds). Any failure is exit 1 and the
runner never starts. Running the tests at start, not at build time, is the point: the
gate re-earns the claim on every start, including every restart after a kill.</p>
"""

METH_HASH = """
<p>Six modules decide every score, and four fixture files pin their golden values. A
sha256 over those ten files is pinned in <code>VERIFIER_HASH</code>; the entrypoint
recomputes it, and every archive record stores the hash that scored it, so a change to
any byte is loud twice over. Drilled, not assumed: pre-flight item A3 altered one line
of <code>coeffrep.py</code> and the container refused with "VERIFIER HASH MISMATCH";
restored, it gated green.</p>
"""

METH_REACH = """
<p>The GitHub credential never enters the container: the env file is filtered on the
host, the runner only commits into the mounted checkouts, and the host watchdog pushes
with the owner's own credentials (an earlier token-scoping design failed its probe;
see <a href="design-decisions.html#credentials">credentials outside the container</a>).
Model-written problems execute only after the quarantine's admission checks, join the
held-out set alone, and shadow for 10 cycles; the check list is on the
<a href="architecture.html">architecture page</a>.</p>
"""

METH_SUITE = """
<p>The suite collects <strong>1,038 tests</strong> in nine numbered tiers that mirror
the dependency stack. Golden tests (G-numbered) pin behaviour to fixture values written
before the build existed, down to exact measured orders and cycle counts. Canary tests
(K-numbered) are anti-gaming: K1 plants a candidate tuned on the search set and asserts
it can earn search_only but never heldout_verified; K2 asserts a single-family winner
stays unreplicated.</p>
"""

METH_PREFLIGHT = """
<p>The pre-flight checklist is not a document anyone initials.
<code>scripts/preflight.py</code> executes every machine-checkable item and writes the
signed report: <strong>91 PASS, 0 FAIL</strong>, 8 MANUAL, 1 advisory INFO on the
2026-08-30 run. The drills act instead of asserting: A1 writes to
<code>/harness</code> from a running container and expects "Read-only file system";
D5 feeds the optimizer the held-out set and watches the search/held-out gap collapse
to zero, then return on revert. Three drills changed the system before the run
started; those stories are under <a href="design-decisions.html">design
decisions</a>.</p>
"""

METH_REPRO = """
<p>The same seed produces byte-identical archives, and an acceptance test requires it.
The evaluator reads no clock and draws no random numbers; the archive is append-only
JSONL whose derived state replays from the files alone; every record stores the hash
of the scoring code that produced it. Storage is UTC everywhere, and only display code
converts to Central time. The findings site is a pure function of the archive: same
records, same bytes.</p>
"""

METH_LIMITS = """
<p>The honest edges, briefly: the cycle model is analytic and has never been closed
against a physical chip inside the loop; measured order comes from one scalar problem
in float64; error is judged at the final time, not along the trajectory; and floor is
one hardware convention among several. Optimality claims from the enumerated phases
hold only within their lattices, and four held-out problems make a strong filter, not
a statistical guarantee. The full list, with reasoning, is on the
<a href="findings/methodology.html">findings methodology page</a>.</p>
"""

# ---------------------------------------------------------------------- design decisions

DECISIONS_LEAD = (
    "Each entry: the original decision from DESIGN.md (written before the build), and "
    "what the working system actually does. Tags mark whether contact with reality kept "
    "or changed it.")

# (anchor_slug, title, original_summary, as_built) — original_summary condensed from
# DESIGN.md; as_built annotates what the code actually does today. Rendered as trusted
# HTML (no user input); slugs are deep-link anchors: stable, short, never reused.
DECISIONS = [
    ("quantization",
     "The problem is quantization, not coefficient prettiness",
     "In floating point, h·b constant-folds and 1/3 costs the same as 0.25; the premise "
     "only survives in fixed point on an FPU-less MCU, where a power-of-two coefficient "
     "becomes a shift. Scope narrowed accordingly.",
     "Kept, and measured: coefficient arithmetic is 50&ndash;56% of per-step cycles under "
     "the fast multiplier, with a roundoff/truncation crossover inside the practical "
     "step-size range (<a href=\"results.html#crossover\">key finding 3</a>)."),
    ("dyadic-theorem",
     "Order ≥ 3 admits no all-dyadic tableau",
     "Dyadic rationals are closed under + and ×; Σ b·c² = 1/3 is not dyadic. "
     "The objective is minimising non-dyadic multiplies subject to order, encoded as "
     "reject code DYADIC_IMPOSSIBLE so the search never wastes a cycle on an empty "
     "region.",
     "Kept, and it shaped the search space itself: A is snapped to dyadics but b is "
     "solved exactly over the rationals from the b-linear order conditions, because "
     "snapping b would run into this very theorem. The verifier rejects all-dyadic "
     "order-3 claims without evaluating them (tests V5&ndash;V7)."),
    ("static-counting",
     "Static cycle counting, not simulation, not hardware",
     "The inner loop is branchless straight-line code, so summing ISA cycle costs gives "
     "an exact count and a genuine WCET figure; host contention cannot corrupt the "
     "metric.",
     "Kept, sharpened: the count is fully analytic from the tableau (no compiler or "
     "disassembly in the loop). The model is anchored to hardware by one hand-counted "
     "ARMv6-M sequence (13 cycles fast / 75 slow) that a test reproduces exactly, and "
     "emit_c exists for a one-time human cross-check."),
    ("targets",
     "Cortex-M0+ primary; AVR advisory; two M0+ multiplier variants",
     "M0+ has no FPU/divide/long-multiply, so fixed point is forced; running a 1-cycle "
     "and a 32-cycle multiplier model costs nothing and turns hardware-aware into a "
     "demonstrated effect if the ranking changes.",
     "Kept; the ranking does change (rk4 33 vs rk38 36 fast; rk38 64 vs rk4 85 slow; the "
     "anchor result on the <a href=\"index.html\">overview</a>). AVR stays advisory in a "
     "stronger sense than planned: after a live candidate was rejected on an AVR-column "
     "infinity, verification was restricted to primary-model columns only; the slow/AVR "
     "numbers are archive breadth."),
    ("q15-overflow",
     "Q15, wrapping semantics, overflow as a rejection",
     "Q31 must be synthesized on M0+; saturation costs a compare-and-branch and destroys "
     "exact counting. Overflow at 2× amplitude is a verifier rejection: a property of "
     "the method, not a runtime cost.",
     "Kept, with one addition the spec missed: rc_thermal's derivative (&minus;11 at "
     "t=0) times its state scale exceeds Q15, so derivatives carry a per-problem "
     "power-of-two scale (DERIV_SCALE, 1/8 there) undone in the step via h. Floor "
     "rounding turned out to be a first-class experimental variable "
     "(<a href=\"results.html#floor-flip\">key finding 2</a>)."),
    ("inner-outer",
     "Classical optimizer in the inner loop, LLM in the outer loop",
     "A 6-parameter space has gradients; CMA-ES beats an LLM mutation operator for free. "
     "The LLM decides what to search and interprets what came back.",
     "Kept, and the boundary held under pressure: when order-4 islands yielded nothing "
     "(exact order-4 b rarely solvable over dyadic A), the fix was a projection fallback "
     "in the optimizer, not more LLM. The outer loop grew: directives every N cycles "
     "with reuse between, a plan-usage cap, model-proposed hypotheses, and a web "
     "literature loop feeding every prompt."),
    ("heldout-split",
     "Search/held-out split, enforced structurally",
     "The optimizer has no code path that reads HELDOUT_SET; the held-out gap is a "
     "first-class dashboard metric so it cannot rot unnoticed.",
     "Kept literally: a test walks the optimizer's import graph and fails on any load of "
     "the name. The D5 drill deliberately feeds the optimizer the held-out set, watches "
     "the gap collapse to zero, and restores it on revert, so the metric measures what "
     "it claims to. The gap is also an honest caveat on the champion numbers "
     "(<a href=\"results.html#efficiency\">key finding 1</a>)."),
    ("map-elites",
     "MAP-Elites, one grid per order",
     "Descriptors are stage count and cycle-cost bucket; a table of results rather than "
     "a single champion.",
     "Kept unchanged; the grids are the spine of the findings site (heatmaps + tables), "
     "and cell incumbency is what tier assignment compares against."),
    ("equal-budget",
     "Equal cycle budget, never equal step size",
     "A 2-stage method gets twice the steps of a 4-stage method for the same cost; "
     "equal-h comparisons are the most common route to a wrong conclusion.",
     "Kept, and it is the frame for every result on the "
     "<a href=\"results.html\">key findings page</a>: the rank flips and the efficiency "
     "frontier only exist at equal budget."),
    ("resource-limits",
     "Fixed resource limits plus a pause watchdog",
     "Low cpu-shares plus docker pause on contention stays out of the way in ~40 lines; "
     "no dynamic allocation, no GPU.",
     "Kept, grown modestly: the watchdog also pauses on battery (owner's rule), "
     "hard-stops on spend/disk, kills on a stale heartbeat, and pushes the two writable "
     "repos from the host. Thresholds live in config.json rather than in code."),
    ("credentials",
     "Credentials outside the container; harness mounted read-only",
     "If the agent can write the verifier, the shortest path to a high score is editing "
     "the scorer. PAT scoped to rk-work and rk-findings; the 403 on rk-harness is an "
     "acceptance test.",
     "Half-kept, half-superseded. The read-only mount and pinned verifier hash stand. "
     "The PAT scoping did not survive contact: the owner's token had contents-write "
     "everywhere, and the handoff's 403 probe passed for the wrong reason (missing "
     "Administration permission). As built, the credential simply never enters the "
     "container: a filtered env file plus host-side pushes, which makes the guarantee "
     "independent of token scope. The scope probe is kept as an advisory check."),
    ("numbers-not-claims",
     "Auto-publish numbers, never claims",
     "The site emits values with mechanically-assigned tiers; a wrong result should be a "
     "wrong number in a table, not a claim requiring retraction.",
     "Amended by the owner, with the guard intact: the findings site now also publishes "
     "model-written interpretation and web-researched literature digests, clearly "
     "labelled and passed through a softener that replaces priority-claim words before "
     "storage. The banned-words guard still hard-fails any page it doesn't like, and it "
     "proved itself by blocking builds over a hypothesis containing 'beats' until the "
     "softener existed."),
    ("encourager",
     "The encourager may change direction but not stop",
     "Before the calendar date it can only redirect, widen, hypothesize, or advance "
     "phase; set-and-forget systems without a calendar run until the operator gets "
     "bored.",
     "Kept: PACKAGE (re-verify everything, no new directions) opens 2026-11-20 and "
     "FREEZE 2026-12-05, property-tested over a thousand random states and exercised "
     "through the real clock path."),
    ("falsification-first",
     "Falsification experiment first",
     "If coefficient arithmetic is swamped by derivative evaluation the thesis is dead; "
     "find out in week one, not month three.",
     "Kept, run, recorded either-way as promised: proceed for rk4 on both counts; heun2 "
     "under the slow model sits at 14.8%, a hair under the 15% line, so the verdict is "
     "stored as 'mixed' rather than rounded up "
     "(<a href=\"results.html#crossover\">key finding 3</a>)."),
]

CUTS = """
<p>Adaptive step size and Newton-iteration implicit methods break the execution-time
certificate hard real-time requires; wrong for the target, not merely unaffordable.
Order &gt; 4 and linear multistep multiply the space with no reason to expect a larger
quantisation effect. Rosenbrock methods remain the natural second project. One addition
to the cut list from the build: alternative rounding modes (round-to-nearest, stochastic
rounding) are deliberately a <em>measured comparison</em> on the key findings page, not a
search dimension, because changing the arithmetic changes every score in the archive, so
it is pinned by the verifier hash.</p>
"""

PRIOR_ART = """
<p>RKTK (Zhang, 2019) already performs unstructured numerical search over Butcher order
conditions and holds an order-10 stage-count record; numerical tableau search is not the
contribution. That line optimises order, stages and error constants in exact arithmetic.
Nobody prices coefficients against a hardware cost model, and nobody evaluates end-to-end
in fixed point; that is the gap, and it is narrow enough to finish. The literature loop
keeps collecting adjacent work (fixed-point ODE solvers, CSD constant multiplication,
rounding-error analysis) into the findings site's literature page as the run proceeds.</p>
"""
